### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by Arnaud-J** [aulasoftwarelibre/nestjs-eventstore#1]
Hi

I have been using this lib for playing around with NestJS and event-sourcing, and I must say it works nicely!

Thus I am wondering what is the state of this project? Do you plan to continue working on it? Would you be open for others to work on it?
Why do you state that it is not ready for production? Do you know some scenarii where it might/will break? What do you feel is missing from the lib's features?

Cheers

**Comment by sgomez** [comment]
Oops, sorry @Arnaud-J. We didn’t notice this message until now.

To be honest, this is more of an internal package for students’ final degree theses rather than a general-use package.

As for whether it’s ready for production, I wouldn’t take the risk of depending on a package that is minimally maintained like this one. If it were more widely used, we could perhaps organize a plan to review it regularly. But GitHub doesn’t show any installations that depend on this package.

Right now, this package only does one thing and does it well (reading/writing from the event store), but to be used in production, I believe we would need some additional features:

* Support for snapshots
* Better tools to rebuild projections in a different collection in a warm state (and perform a hot switch)

Again, sorry for not responding sooner.
